fix(client+server): add return cash only settlement action, fixes #168
ilmercatinodellibro/ilmercatinodellibro pull request #200
Opened 2024-12-02 12:48 UTC by andrea-cerlini

fixes #168

## What it does
This feature adds a new button to the payoff dialog actions to return the money of the unsettled sold books without returning/changing ownership of the books of the customer that are still in stock.

## How to test it
From the users management page, click on the checkout button for a user with sold books, then press the button to return cash only

### Additional notes
The label for the confirmation may need further checks on the wording

2024-12-02 16:06 UTC, IlCallo requested changes

2024-12-02 16:06 UTC, IlCallo commented on packages/client/src/components/manage-users/pay-off-user-dialog.vue
> +      evictQuery(cache, GetSoldBookCopiesDocument);
Why is this required?
We're not removing sold books

I guess this was part of the previous implementation for which you hid the settled sales

2024-12-02 16:06 UTC, IlCallo commented on packages/client/src/i18n/it/manage-users.ts
>      returnAndDonate: "Restituisci contanti e dona libri",
Why isn't there the amount to return here? I guess we should add it

@NiccoloMenozzi this seems something that has been decided into design phase, as it has been implemented as per mockup

"Return cash only" is the new button we added

Actual
![image](https://github.com/user-attachments/assets/80cdee3f-459d-4e90-b4e5-abc08ec3fdaa)

Zeplin
![image](https://github.com/user-attachments/assets/ce61ea14-2f78-4a2b-b7de-859a48e9c0c4)

2024-12-04 17:01 UTC, andrea-cerlini commented on packages/client/src/components/manage-users/pay-off-user-dialog.vue
> +      evictQuery(cache, GetSoldBookCopiesDocument);
This is needed to update the local cache's status regardless, just like in `returnAllBooks` (even though there `refetch` is called instead); should I add the same comment, change it with a `refetch` call, or leave it as it is?

2024-12-18 09:51 UTC, IlCallo commented on packages/client/src/components/manage-users/pay-off-user-dialog.vue
> +      evictQuery(cache, GetSoldBookCopiesDocument);
Let's leave it as is, it works, I'll try to better understand how it actually works later on

2024-12-18 09:53 UTC, IlCallo commented on packages/client/src/i18n/it/manage-users.ts
>      returnAndDonate: "Restituisci contanti e dona libri",
I added the amount in all buttons

2024-12-18 10:16 UTC, merged